FROM robertsmieja/dev-nodejs

# For puppeteer
# RUN apk add --no-cache \
#     ffmpeg \
#     chromium \
#     ttf-freefont \
#     ca-certificates

# For node-gyp
# RUN apk add --no-cache --virtual build-dependencies \
#    python \
#    build-base
